boards/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('list/',views.BoardListView.as_view(),name="board_list"),
    path('<int:pk>/',views.BoardDetailView.as_view(),name="board_detail"),
    path("create/",views.BoardCreateView.as_view(),name="board_create"),
    path("<int:board_pk>/edit/", views.BoardUpdateView.as_view(), name="board_edit"),
    path("<int:board_pk>/delete/", views.board_delete, name="board_delete"),
    path('tag/search/',views.TagSearchView,name='tag_search')
]

config/urls.py
from django.contrib import admin
from boards import views
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('boards/',include('boards.urls',namespace='board'))
]

boards/models.py
from django.db import models

class Board(models.Model):
    title = models.CharField(max_length=50,verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    tag = models.ManyToManyField("Tag",blank=True,verbose_name="태그")
    writer = models.ForeignKey("users.User",related_name="boards",verbose_name="작성자",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="생성날짜")  
    updated_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")  
    class Meta:
        verbose_name_plural = "게시판"
    def __str__(self):
        return self.title

class Tag(models.Model):
    name = models.CharField(max_length=30,verbose_name="태그이름")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="생성날짜")  
    class Meta:
        verbose_name_plural = "태그"
    
    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class GenderChoice(models.TextChoices):
        male = ("M","남자")
        female = ("F","여자")
    first_name = None
    last_name = None
    name = models.CharField(max_length=20,blank=True,null=True,verbose_name="이름")
    birthday = models.DateField(null=True, blank=True, verbose_name="생년월일")
    gender = models.CharField(max_length=10,choices=GenderChoice.choices,verbose_name="성별")
    phone_number = models.CharField(validators=[RegexValidator(r'010-?[1-9]\d{3}-?\d{4}$')], max_length=13, blank=True)

boards/forms.py
from django import forms
from . import models as boards_models


class BoardCreateForm(forms.ModelForm):
    class Meta:
        model = boards_models.Board
        fields = [
           "title",
            "content",
            "tag",
        ]
    tag = forms.ModelMultipleChoiceField(queryset=boards_models.Tag.objects.all(), widget=forms.CheckboxSelectMultiple,label="태그")
    def save(self):
        board = super().save(commit=False)
        return board


class TagSearchForm(forms.ModelForm):
    class Meta:
        model = boards_models.Tag
        fields = [
            "name"
        ]
    name = forms.ModelMultipleChoiceField(queryset=boards_models.Tag.objects.all(), widget=forms.CheckboxSelectMultiple,label="태그목록")

boards/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.urls import reverse
from . import models as boards_models
from . import forms as boards_forms
from django.views.generic import DetailView,FormView,ListView,UpdateView


def home(request):
    return render(request,'home.html',{})

class BoardListView(ListView):
    model = boards_models.Board
    paginate_by = 5  # 페이지당 8개
    paginate_orphans = 3 # 마지막 페이지에 3개 이하가 남겨져 있으면 앞페이지로 당겨짐 마지막 페이지에는 (8 + 3이하)개의 게시물이 있음
    template_name: str = 'boards/board_list.html'
    def get_queryset(self):
        boards = boards_models.Board.objects.order_by('-created_at')
        return boards
    def get_context_data(self, **kwargs):
        context = super(BoardListView, self).get_context_data()
        page = context['page_obj']
        paginator = page.paginator
        pagelist = paginator.get_elided_page_range(page.number, on_each_side=3, on_ends=0)
        context['pagelist'] = pagelist
        return context

class BoardDetailView(DetailView):
    model = boards_models.Board
    template_name: str = 'boards/board_detail.html'
    def get_object(self):
        board = get_object_or_404(boards_models.Board, pk=self.kwargs["pk"])
        return board


class BoardCreateView(FormView):
    template_name = "boards/board_create.html"
    form_class = boards_forms.BoardCreateForm
    queryset = boards_models.Board
    def form_valid(self, form):
        board = form.save()
        board.writer = self.request.user
        board.save()
        form.save_m2m()
        return redirect(reverse("board:board_detail", kwargs={"pk": board.pk}))
    
class BoardUpdateView(UpdateView):
    model = boards_models.Board
    template_name = "boards/board_edit.html"
    fields = (
        "title",
        "content",
        "tag",
    )
    def get_success_url(self):
        board_pk = self.kwargs.get("board_pk")
        return reverse(
            "board:board_detail",
            kwargs={
                "pk": board_pk,
            },
        )
    def get_object(self):
        board = get_object_or_404(boards_models.Board, pk=self.kwargs["board_pk"])

        return board


def board_delete(request, board_pk):
    board = boards_models.Board.objects.get(pk=board_pk)
    board.delete()
    return redirect("board:board_list")


def TagSearchView(request):
    if request.method == "GET":
        form=boards_forms.TagSearchForm()
    else:
        form = boards_forms.TagSearchForm(request.POST)
        if form.is_valid():
            tags = form.cleaned_data.get('name')
            tag = get_object_or_404(tags)
            boards_list = boards_models.Board.objects.filter(tag__name__icontains=tag).order_by('-pk')
            page = request.GET.get('page','1')
            paginator = Paginator(boards_list,per_page=5,orphans=3) # 페이지당 5개
            page_obj = paginator.get_page(page)
            return render(request,'tag/tag_search.html',{'form':form,'boards_list':boards_list,'page_obj':page_obj,"tag":tag})
    return render(request,'tag/tag_search.html',{'form':form})

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--bootstrap5-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- tailwindcss-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block page_name %}{% endblock page_name %}</title>
</head>
<body>
    <div class = "t-my-10">
        <a class="t-ml-10" href="{% url 'board:board_create' %}">새글 쓰기</a>
        <a href="{% url 'board:tag_search' %}">모든 태그 보기</a>
    </div>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/boards/board_create.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <button type="submit" class="btn btn-outline-secondary">등록하기</button>
</form>
{% endblock content %}

templates/boards/board_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ board.title }}</h2>
    <a href="{% url 'board:board_edit' board.pk %}">수정하기</a>
    <a href="{% url 'board:board_delete' board.pk %}">삭제하기</a>
    <div class=" p-1">
    <p>생성일 : {{ board.created_at }}</P>
    <p>수정일 : {{ board.updated_at }}</p>
    </div>
    <div class="card my-3">
        <!-- tag 넣을 자리-->
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ board.content }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/boards/board_edit.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST" action="{% url 'board:board_edit' board.pk %}">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <button type="submit" class="btn btn-outline-secondary">수정하기</button>
    </form>
{% endblock content %}

templates/boards/board_list.html
{% extends 'base.html' %}

{% block page_name %}
hongsub's blog
{% endblock page_name %}

{% block content %}
<div class="card" style="width: full;">
    {% if object_list %}
    {% for board in object_list %}
    <div class="card w-75 m-1">
      <div class="card-body">
        <h5 class="card-title">{{board.title}}</h5>
        <p class="card-text">{{board.content}}</p>
        {% if board.tag.all %}
            {% for tag in board.tag.all  %}
            <h10 class="card-text t-text-sm">{{tag}}</h10>
        {% endfor %}
        {% endif %}
        <a href='{% url 'board:board_detail' board.pk %}' class="btn btn-primary">들어가기</a>
      </div>
    </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
  <ul class="pagination justify-content-center mb-4">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
    </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#">이전</a>
    </li>
        {% endif %}

    {% for index in pagelist %}
        {% if index == page_obj.number %}
    <li class="page-item active">
        <span class="page-link">{{ index }}</span>
    </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ index }}">{{ index }}</a>
        </li>
        {% endif %}
    {% endfor %}

        {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
    </li>
        {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#">다음</a>
    </li>
        {% endif %}
  </ul>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class = 't-flex t-justify-center'>
<h1> 안녕하세요 hongsub's 블로그입니다</h1>
</div>
홍섭이의 블로그를 둘러 보고싶다면?
<a href ="{% url 'board:board_list' %}">여기 눌러주세요</a>
{% endblock content %}

templates/tag/tag_search.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" action="{% url 'board:tag_search' %}">
    {% csrf_token %}
    <div class="t-flex">
        {{form.as_p}}
    </div>
    <button type="submit" class="btn btn-outline-secondary">검색</button>
</form>
    <div class ="t-flex t-justify-center t-text-xl"> {{tag}} 의 검색 결과입니다 </div>
    <div class="t-flex t-flex-col t-justify-items-center ">
        {% if boards_list %}
            {% for board in boards_list %}
                <div class="card w-75 m-1">
                    <div class="card-body">
                      <h5 class="card-title">{{board.title}}</h5>
                      <p class="card-text">{{board.content}}</p>
                      {% if board.tag.all %}
                          {% for tag in board.tag.all  %}
                          <h10 class="card-text t-text-sm">{{tag}}</h10>
                      {% endfor %}
                      {% endif %}
                      <a href='{% url 'board:board_detail' board.pk %}' class="btn btn-primary">들어가기</a>
                    </div>
                  </div>
            {% endfor %}
    </div>
    </div>
    <ul class="pagination justify-content-center mb-4">
        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
        </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#">이전</a>
        </li>
            {% endif %}
        {% for index in page_obj.paginator.page_range %}
            {% if index == page_obj.number %}
        <li class="page-item active">
            <span class="page-link">{{ index }}</span>
        </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ index }}">{{ index }}</a>
            </li>
            {% endif %}
        {% endfor %}
    
    
            {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
        </li>
            {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#">다음</a>
        </li>
            {% endif %}
      </ul>
    {% endif %}
{% endblock content %}